### PR TITLE
Sentry Mode Switch Option

### PR DESCRIPTION
**Pull request by farhad-a**
Added a configuration option to load Sentry Mode as a switch, instead of a lock. The default is still a lock.

### CODE REVIEW

**Comment by nfarina** [comment]
Looks great! But curious, why have it as a switch? The side benefit to making it a lock is no one can pick up your phone or yell into your HomePod to control the car.

**Comment by farhad-a** [comment]
Thank you! I realize my use case may not be in the majority and think the lock mechanism is a good fit and should remain the default option. In my case, I don't use Sentry Mode while at home. So when I ask Siri to "lock all the doors," Sentry Mode turns on. Or if I ask "are all the doors are locked?" Siri reports the unlocked Sentry Mode.

**Comment by farhad-a** [comment]
Does that use-case make sense? Please let me know if there are any issues I could remedy. Or, questions I could help address.

**Comment by nfarina** [comment]
I've come around on this - I think the switch actually makes more sense. But also like having the option for folks who prefer the lock. Thanks so much for writing this up and sorry it took so long to merge!

**Comment by farhad-a** [comment]
Thanks for accepting. And thank you so much for all you have done for the community.

**Pull request merged**
